using UseCases.Common.Security.Authorization.Attributes;

namespace UseCases.Common.Security.Authorization.Configuration;

/// <summary>
/// Builder for creating authorization configurations in a fluent way.
/// Provides a convenient API for building complex authorization requirements.
/// </summary>
public sealed class AuthorizationBuilder
{
    private readonly List<string> _permissions = [];
    private readonly List<string> _roles = [];
    private readonly List<string> _policies = [];

    /// <summary>
    /// Adds a required permission.
    /// </summary>
    /// <param name="permission">Permission to require</param>
    /// <returns>This builder for method chaining</returns>
    public AuthorizationBuilder RequirePermission(string permission)
    {
        if (!string.IsNullOrWhiteSpace(permission))
        {
            _permissions.Add(permission);
        }
        return this;
    }

    /// <summary>
    /// Adds multiple required permissions.
    /// </summary>
    /// <param name="permissions">Permissions to require</param>
    /// <returns>This builder for method chaining</returns>
    public AuthorizationBuilder RequirePermissions(params string[] permissions)
    {
        if (permissions != null)
        {
            _permissions.AddRange(permissions.Where(p => !string.IsNullOrWhiteSpace(p)));
        }
        return this;
    }

    /// <summary>
    /// Adds a required role.
    /// </summary>
    /// <param name="role">Role to require</param>
    /// <returns>This builder for method chaining</returns>
    public AuthorizationBuilder RequireRole(string role)
    {
        if (!string.IsNullOrWhiteSpace(role))
        {
            _roles.Add(role);
        }
        return this;
    }

    /// <summary>
    /// Adds multiple required roles.
    /// </summary>
    /// <param name="roles">Roles to require</param>
    /// <returns>This builder for method chaining</returns>
    public AuthorizationBuilder RequireRoles(params string[] roles)
    {
        if (roles != null)
        {
            _roles.AddRange(roles.Where(r => !string.IsNullOrWhiteSpace(r)));
        }
        return this;
    }

    /// <summary>
    /// Adds a required policy.
    /// </summary>
    /// <param name="policy">Policy to require</param>
    /// <returns>This builder for method chaining</returns>
    public AuthorizationBuilder RequirePolicy(string policy)
    {
        if (!string.IsNullOrWhiteSpace(policy))
        {
            _policies.Add(policy);
        }
        return this;
    }

    /// <summary>
    /// Adds multiple required policies.
    /// </summary>
    /// <param name="policies">Policies to require</param>
    /// <returns>This builder for method chaining</returns>
    public AuthorizationBuilder RequirePolicies(params string[] policies)
    {
        if (policies != null)
        {
            _policies.AddRange(policies.Where(p => !string.IsNullOrWhiteSpace(p)));
        }
        return this;
    }

    /// <summary>
    /// Builds the authorization attribute with the configured requirements.
    /// </summary>
    /// <returns>RequestAuthorizeAttribute with the configured requirements</returns>
    /// <exception cref="InvalidOperationException">Thrown when no requirements are configured</exception>
    public RequestAuthorizeAttribute Build()
    {
        if (_permissions.Count == 0 && _roles.Count == 0 && _policies.Count == 0)
        {
            throw new InvalidOperationException("At least one authorization requirement must be configured.");
        }

        string? permissions = _permissions.Count > 0 ? string.Join(",", _permissions) : null;
        string? roles = _roles.Count > 0 ? string.Join(",", _roles) : null;
        string? policies = _policies.Count > 0 ? string.Join(",", _policies) : null;

        return new RequestAuthorizeAttribute(permissions, roles, policies);
    }

    /// <summary>
    /// Gets the policy string that would be generated by this builder.
    /// Useful for debugging or caching scenarios.
    /// </summary>
    /// <returns>Policy string</returns>
    public string GetPolicyString()
    {
        return Build().Policy ?? throw new InvalidOperationException("Policy string cannot be null");
    }

    /// <summary>
    /// Creates a new authorization builder.
    /// </summary>
    /// <returns>New AuthorizationBuilder instance</returns>
    public static AuthorizationBuilder Create() => new();

    /// <summary>
    /// Creates a builder pre-configured for admin access.
    /// </summary>
    /// <param name="resource">Optional specific resource for granular admin permissions</param>
    /// <returns>AuthorizationBuilder configured for admin access</returns>
    public static AuthorizationBuilder ForAdmin(string? resource = null)
    {
        AuthorizationBuilder builder = new AuthorizationBuilder()
            .RequireRole("Administrator");

        if (!string.IsNullOrWhiteSpace(resource))
        {
            builder.RequirePermission($"Admin.{resource}.Manage");
        }
        else
        {
            builder.RequirePermission("Admin.Manage");
        }

        return builder;
    }

    /// <summary>
    /// Creates a builder pre-configured for user management operations.
    /// </summary>
    /// <returns>AuthorizationBuilder configured for user management</returns>
    public static AuthorizationBuilder ForUserManagement() =>
        Create()
            .RequirePermissions("Admin.User.Create", "Admin.User.Update", "Admin.User.Delete")
            .RequireRole("UserManager");

    /// <summary>
    /// Creates a builder pre-configured for role management operations.
    /// </summary>
    /// <returns>AuthorizationBuilder configured for role management</returns>
    public static AuthorizationBuilder ForRoleManagement() =>
        Create()
            .RequirePermissions("Admin.Role.Create", "Admin.Role.Update", "Admin.Role.Delete")
            .RequireRole("RoleManager");

    /// <summary>
    /// Resets the builder to its initial state.
    /// </summary>
    /// <returns>This builder for method chaining</returns>
    public AuthorizationBuilder Reset()
    {
        _permissions.Clear();
        _roles.Clear();
        _policies.Clear();
        return this;
    }

    /// <summary>
    /// Returns a summary of the current configuration.
    /// </summary>
    /// <returns>String describing the current configuration</returns>
    public override string ToString()
    {
        List<string> parts = [];

        if (_permissions.Count > 0)
            parts.Add($"Permissions: [{string.Join(", ", _permissions)}]");

        if (_roles.Count > 0)
            parts.Add($"Roles: [{string.Join(", ", _roles)}]");

        if (_policies.Count > 0)
            parts.Add($"Policies: [{string.Join(", ", _policies)}]");

        return parts.Count > 0 ? string.Join(", ", parts) : "No requirements configured";
    }
}