<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>SharedKernel.UnitTests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
    
  <ItemGroup>
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
    
  <ItemGroup>
    <Reference Include="Serilog">
      <HintPath>..\..\..\..\..\.nuget\packages\serilog\4.3.0\lib\net9.0\Serilog.dll</HintPath>
    </Reference>
  </ItemGroup>
    
  <ItemGroup>
    <Folder Include="Domain\ValueObjects\" />
  </ItemGroup>

</Project>
